### ISSUE TITLE
Unsupported API version 1.16

### ISSUE THREAD

**Issue by TheNety** [SpraxDev/BetterChairs#16]
Paper 1.15.2
BetterChairs v0.11.2

Hey, got that error and plugin couldn't load because of that.

`[03:27:36] [Server thread/ERROR]: Could not load 'plugins/BetterChairs.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.16
     at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:276) ~[patched_1.15.2.jar:git-Paper-375]
     at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.15.2.jar:git-Paper-375]
     at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-375]
     at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-375]
     at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-375]
     at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-375]
     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-375]
     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]`

**Comment by SpraxDev** [comment]
My bad - I'll publish a fix shortly.

**Comment by SpraxDev** [comment]
This bug has been fixed in v0.11.3 - Please download it from https://github.com/SpraxDev/BetterChairs/releases
