### ISSUE TITLE
Rightclick on a sign triggerd error sometimes

### ISSUE THREAD

**Issue by MAH1987** [SpraxDev/BetterChairs#81]
* **Server Version**: git-Paper-342 (MC: 1.16.4)
* **Plugin Version**: BetterChairs version 1.2.0

**Describe the bug**
if i rightclick on a sign sometimes better-chair triggers the error below. 

**Screenshots, Videos, Logs or Errors**
```
[18:04:39 ERROR]: Could not pass event PlayerInteractEvent to BetterChairs v1.2.0
java.lang.IllegalArgumentException: Cannot measure distance between Mall and Spawn
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.4.jar:git-Paper-342]
        at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.4.jar:git-Paper-342]
        at de.sprax2013.betterchairs.EventListener.onInteract(EventListener.java:104) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Paper-342]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-342]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-342]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-342]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:464) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1549) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-342]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by SpraxDev** [comment]
I can't reproduce that error but it might occur in combination with the player being teleported because he right-clicked the sign.

Could you please try the attached file and report back if the error seems to be fixed?

[BetterChairs.zip](https://github.com/SpraxDev/BetterChairs/files/5748763/BetterChairs.zip)

**Comment by MAH1987** [comment]
Hy @SpraxDev, 
Thank you for your answer and really fast help! I I didn't expect any answer between the years.

The new version works fine and the error seams gone. 

Many thanks and great work!
